---
- name: Configure Apache with error handling
  hosts: ubuntu
  become: yes
  tasks:

    - name: Block to install and configure Apache
      block:
        - name: Install apache2 package
          apt:
            name: apache2
            state: present
        - name: Start apache2 service
          service:
            name: apache2
            state: started

      rescue:
        - name: Handle failure - Report error
          debug:
            msg: "Apache installation or service start failed"

      always:
        - name: Ensure Apache is stopped if failed
          service:
            name: apache2
            state: stopped
