---
- name: Add users and assign to groups
  hosts: ubuntu
  become: true
  vars:
    users:
      - user1
      - user2
      - user3
      - user4

  tasks:
    - name: Add users to the system
      user:
        name: "{{ item }}"
        state: present
      loop: "{{ users }}"

    - name: Add user1 to the sales group
      user:
        name: "{{ item }}"
        groups: sales
        append: yes
      changed_when: item == 'user1'
      loop: "{{ users }}"
