---
- name: Add users and assign to groups
  hosts:  ubuntu
  become: true
  gather_facts: yes
  vars:
    users:
      - user1
      - user2
      - user3
      - user4

  tasks:
    - name: "Add users to the system"
      block:
        - name: "Add user {{ item }} to the system"
          user:
            name: "{{ item }}"
            state: present
          changed_when: true
          ignore_errors: yes
        - name: "Set fact for user {{ item }} to check group membership"
          set_fact:
            user_is_in_sales: "{{ 'sales' in ansible_facts['user_groups'][item] }}"
          when: item == 'user1'
      loop: "{{ users }}"
      ignore_errors: yes

    - name: "Add user1 to the sales group if not already a member"
      block:
        - name: "Ensure user1 is in the sales group"
          user:
            name: user1
            groups: sales
            append: yes
          changed_when: "{{ not user_is_in_sales }}"
          ignore_errors: yes
      when: "'user1' in users"
