---
- name: Add users and assign to groups
  hosts: ubuntu
  become: true
  gather_facts: yes  # Ensures facts about the system are gathered
  vars:
    users:
      - user1
      - user2
      - user3
      - user4

  tasks:
    - name: Add users to the system
      user:
        name: "{{ item }}"
        state: present
      loop: "{{ users }}"
      changed_when: true  # Always mark as changed, assuming user creation or modification
      ignore_errors: yes  # Ignore errors for user creation tasks

    - name: Add user1 to the sales group
      user:
        name: "{{ item }}"
        groups: sales
        append: yes
      when: item == 'user1'
      loop: "{{ users }}"
      changed_when: >
        item == 'user1' and 
        (ansible_facts['user_groups'][item] is not defined or 'sales' not in ansible_facts['user_groups'][item])
      ignore_errors: yes  # Ignore errors for group addition tasks
